version: '3.8'
services:
  backend:
    build:
      context: ./codeforge-backend  
      dockerfile: Dockerfile
    container_name: codeforge-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./codeforge-client
      dockerfile: Dockerfile
    container_name: codeforge-client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - HOST=0.0.0.0
      - NODE_ENV=development     
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge